package tr.com.ca.ws.employee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-12T21:24:54.445+03:00
 * Generated source version: 3.3.4
 *
 */
@WebServiceClient(name = "EmployeeService",
                  wsdlLocation = "file:/C:/Users/CIHAN/Desktop/ENVIRONMENTS/ENV_20200111/workspace/JaxWTopDownCXF/src/main/resources/wsdl/EmployeeService.wsdl",
                  targetNamespace = "http://employee.ws.ca.com.tr/")
public class EmployeeService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://employee.ws.ca.com.tr/", "EmployeeService");
    public final static QName EmployeePort = new QName("http://employee.ws.ca.com.tr/", "EmployeePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/CIHAN/Desktop/ENVIRONMENTS/ENV_20200111/workspace/JaxWTopDownCXF/src/main/resources/wsdl/EmployeeService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/CIHAN/Desktop/ENVIRONMENTS/ENV_20200111/workspace/JaxWTopDownCXF/src/main/resources/wsdl/EmployeeService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmployeeService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "EmployeePort")
    public EmployeeService getEmployeePort() {
        return super.getPort(EmployeePort, EmployeeService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeService
     */
    @WebEndpoint(name = "EmployeePort")
    public EmployeeService getEmployeePort(WebServiceFeature... features) {
        return super.getPort(EmployeePort, EmployeeService.class, features);
    }

}
