
package tr.com.ca.ws.employee;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-12T21:24:54.380+03:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "EmployeeAlreadyExists", targetNamespace = "http://employee.ws.ca.com.tr/")
public class EmployeeAlreadyExistsException_Exception extends Exception {

    private tr.com.ca.ws.employee.EmployeeAlreadyExistsException employeeAlreadyExists;

    public EmployeeAlreadyExistsException_Exception() {
        super();
    }

    public EmployeeAlreadyExistsException_Exception(String message) {
        super(message);
    }

    public EmployeeAlreadyExistsException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EmployeeAlreadyExistsException_Exception(String message, tr.com.ca.ws.employee.EmployeeAlreadyExistsException employeeAlreadyExists) {
        super(message);
        this.employeeAlreadyExists = employeeAlreadyExists;
    }

    public EmployeeAlreadyExistsException_Exception(String message, tr.com.ca.ws.employee.EmployeeAlreadyExistsException employeeAlreadyExists, java.lang.Throwable cause) {
        super(message, cause);
        this.employeeAlreadyExists = employeeAlreadyExists;
    }

    public tr.com.ca.ws.employee.EmployeeAlreadyExistsException getFaultInfo() {
        return this.employeeAlreadyExists;
    }
}
