
package tr.com.ca.ws.employee;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-12T21:24:54.333+03:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "EmployeeNotFound", targetNamespace = "http://employee.ws.ca.com.tr/")
public class EmployeeNotFoundException_Exception extends Exception {

    private tr.com.ca.ws.employee.EmployeeNotFoundException employeeNotFound;

    public EmployeeNotFoundException_Exception() {
        super();
    }

    public EmployeeNotFoundException_Exception(String message) {
        super(message);
    }

    public EmployeeNotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public EmployeeNotFoundException_Exception(String message, tr.com.ca.ws.employee.EmployeeNotFoundException employeeNotFound) {
        super(message);
        this.employeeNotFound = employeeNotFound;
    }

    public EmployeeNotFoundException_Exception(String message, tr.com.ca.ws.employee.EmployeeNotFoundException employeeNotFound, java.lang.Throwable cause) {
        super(message, cause);
        this.employeeNotFound = employeeNotFound;
    }

    public tr.com.ca.ws.employee.EmployeeNotFoundException getFaultInfo() {
        return this.employeeNotFound;
    }
}
