
package tr.com.ca.ws.employee;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-01-12T21:24:54.352+03:00
 * Generated source version: 3.3.4
 */

@WebFault(name = "SOAPException", targetNamespace = "http://employee.ws.ca.com.tr/")
public class SOAPException_Exception extends Exception {

    private tr.com.ca.ws.employee.SOAPException soapException;

    public SOAPException_Exception() {
        super();
    }

    public SOAPException_Exception(String message) {
        super(message);
    }

    public SOAPException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SOAPException_Exception(String message, tr.com.ca.ws.employee.SOAPException soapException) {
        super(message);
        this.soapException = soapException;
    }

    public SOAPException_Exception(String message, tr.com.ca.ws.employee.SOAPException soapException, java.lang.Throwable cause) {
        super(message, cause);
        this.soapException = soapException;
    }

    public tr.com.ca.ws.employee.SOAPException getFaultInfo() {
        return this.soapException;
    }
}
